var Discord = require('discord.js');

// Initialize Discord Bot
const bot = new Discord.Client();
bot.on('ready', () => {
    console.log("looged in");
});

bot.on('message', msg => {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (msg.content.substring(0, 1) == '!') {
        var args = msg.content.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'z':
                msg.channel.send('zane is the best programmer evie knows')
            break;
        case 'j':
                var bestQuote = [
                    "13 year olds are the meanest people in the world. They terrify me to this day.", 
                    "Anyone who’s seen my dick and met my parents needs to die. I can’t have them roaming around.",
                    "You have the moral backbone of a chocolate éclair.",
                    "We’ve been on the road for three hours. And in the distance, we see a McDonald’s. We see the golden arches. And we got so excited. We started chanting, 'McDonald’s! McDonald’s! McDonald’s! McDonald’s!' And my dad pulled into the drive-thru, and we started cheering. And then, he ordered one black coffee for himself. And kept driving.",
                    "Why do people shush animals? They've never spoken",
                    "Honestly, when I’m walking down the street, no one’s ever like, 'Hey, look at that man!' I think they’re just like 'Whoa! That tall child looks terrible!'",
                    "Because if you watch cartoons, quicksand is like the third biggest thing you have to worry about in adult life, behind real sticks of dynamite and giant anvils falling on you from the sky.",
                    "Ey, if you’re comin’ to visit, take I-90 ‘cause I-95 has a little quicksand in the middle.",
                    "Luckily, I had a good alibi since I was in Wisconsin and 12.",
                    "That would be like if you’re going out of town for the week and you paid a horse to watch your dog.",
                    "You seen this shit? You seen this Home Alone 2: Lost in New York shit? It’s a grid system, motherfucker! Where you at? 24th and 5th? Where you wanna go? 35th and 6th? 11 up and 1 over, you simple bitch!!",
                    "I think the bullying that young people have to go through now is really rough, I really sympathize, ‘cause I was bullied when I was a kid. When I was in grade school, I was bullied for being Asian-American. Aaaand, the biggest problem with that… is that I am not Asian-American.",
                    "If I’m on the street on like a Friday at 3 PM and I see a group of 8th graders on one side of the street, I will cross to the other side of the street.",
                    "8th graders will make fun of you, but in an accurate way. They will get to the thing that you don’t like about you. They don’t even need to look at you for long, they’ll just be like, 'Ha ha ha ha ha! Ha ha ha ha ha! Hey, look at that high-waisted man! He got feminine hips!",
                    "Now when people make fun of me, I deserve it.",
                    "When people get mad at me now, it’s my fault, when people get mad at me on the highway that’s all my bad, I’m a terrible driver, I know nothing about cars.",
                    "I’m one of the worst drivers I’ve ever seen, and I just want you all to know that if you’re ever on the highway behind me, uh, I hear you honking and I also don’t want me to be doing what I’m doing. I don’t like that I’m in that lane either, and I sure would like to get out of it!",
                    "Cars were pulling up and looking over to see who just did that piece of shit move, expecting to see like a 100-year-old blind dog who’s texting while driving and drinking a smoothie, instead they see a 28-year-old healthy man trying his best.",
                    "No, you can’t say like the 'f'-word, you can’t say that on Special Victims Unit, but people walk around on SVU going like, 'Looks like the victim had anal contusions. Yo, looks like we found semen and fecal matter in the victim's ear canal.",
                    "Or like when some smokes too many cigarettes? Or like when someone shops too much with credit cards? Or like when someone plays too many scratchy lotteries? Or like when someone eats too much chocolate cake? Or like when someone eats too much chocolate cake and then barfs it up?",
                    "A couple years ago, I saw this movie called Public Enemies with Johnny Depp, it was about old bank robbers and stuff. Here’s how easy it was to get away with bank robbery back in the 30’s. As long as you weren’t still there when the police arrived, you had a 99% chance of getting away with it.",
                    "'Ha ha ha! And if anyone asks, you tell em it was Golden Joe and the Suggins Gang!' And then they like shoot 'Suggins' into the side of the wall. It’s like, what, were bullets free back then?",
                    "Percentage-wise, it is 100% easier not to do things than to do them. And so much fun not to do them! Especially when you are supposed to do them. In terms of, like, instant relief, cancelling plans is like heroin. It is an amazing feeling. Such instant joy.",
                    "Uhh, the New York Post is my favorite newspaper. I think it’s great, I read it every day. I like reading the New York Post because reading the New York Post is like talking to someone who heard the news, and now they’re trying to give you the gist.",
                    "My dad came home from work, and my mom told my dad that she had cleaned under my bed and found a shoebox with two cigarettes and a Cosmopolitan to which prompted my dad to ask, 'How does John know how to make a cosmopolitan?'",
                    "Sometimes when people order fries, [playfully] they act like it’s a little adventure. They’ll be like, 'Should we get a plate of fries for the table? Should we do it? Should we-should we share some fries?' They gotta make sure that everyone’s onboard with it, it’s like, 'If I get fries, you’ll have a couple, right? If I get fries for the table, you’ll have — I know you’ll have fries if I get fries — should we do it? Yeah, let’s be bad! C’mon, let’s do it, all right, we’re gonna take a plate of fries!",
                    "Like I try to travel alone sometimes you know and I’ll put up with anything. Like I'll book a ticket on some garbage airline. You know I don’t want to name any actual airline so lets just make one up and so let's just call it Delta Airlines.",
                    "We all ran in different directions, I ran into the laundry room and I jumped up on the washing machine and I crawled out through a window into the backyard and now I’m running through the backyard and there was this big chain link fence and I thought, 'I’ve never climbed a fence that high before.' And then I woke up at home.",
                    "I have a lot of strange interactions on the street. Years ago, I was walking down the street and a homeless guy came up to me. And he walked up to me he pushed me like that, he pushed me in the chest. And then he said these things in this order. He pushed me and he said, 'Excuse me, I am homeless, I am gay, I have aids, I’m new in town.'",
                    "It was as if a ghost had been trapped in my belly and finally flew out towards the light.",
                    "The moral of the story is… that if you’ve been nervous your entire life, you should ask your doctor about Xanax because if you lie to him, he will stick his finger in your ass. And if you do suffer from frequent urination, keep it to yourself.",
                    "Because I was over on the bench!!!",
                    "We invite a woman here with homemade puppets to teach you about bullying through skits and you laugh at this woman? We noticed you had all been bullying each other and making fun of everything constantly. So we invite a woman with straight gray hair, in a denim dress, with a wrist-cast and homemade puppets that all have the same voice to teach you about bullying through skits, and you, ha-ha-ha, laugh it up. What was so funny about that woman? I want to know. What was so funny about when she couldn’t fit the box of puppets back into the trunk of her Dodge Neon? What was so hilarious that you all ran to the windows? Well, you all missed a valuable lesson on the danger of cliques.",
                    "The greatest assembly of them all, once a year, Stranger Danger. Yeah, the hottest ticket in town. The Bruno Mars of assemblies. You are gathered together as a school and you are told never to talk to an adult that you don’t know and you are told this by an adult that you don’t know.",
                    "Bittenbinder wore three-piece suits. He also wore a pocket watch. Two years in a row, he wore a cowboy hat. He also had a huge handlebar mustache. None of that matters, but it’s important to me that you know that. He did not look like his job description. He looked like he should be the conductor on a locomotive powered by confetti. But, instead, he made his living in murder. He was the weirdest goddamn person I ever saw in my entire life. He was a man most acquainted with misery. He could look at a child and guess the price of their coffin.",
                    "So Bittenbinder came every year with a program to teach us about the violent world waiting for us outside the school gym, and that program was called Street Smarts! 'Time for Street Smarts with Detective JJ Bittenbinder. Shut up! You’re all gonna die. Street Smarts!' That was the general tone. He would give us tips to deal with crime.",
                    "Bittenbinder, he didn’t want us to not get kidnapped. He wanted us to almost get kidnapped and then fight the guy off using weird, psych-out, back-room Chicago violence.",
                    "I am 35 years old and I am still terrified of secondary locations. If I’m at a place, I never want to go to another place.",
                    "You see, what had happened, New York, was that when I was a student, I had paid them tuition money. Every semester, two semesters a year, for four years. I don’t remember exactly what it was, but rounding up, back in 1999 dollars, it was about $15,000 a semester, two semesters a year, for four years. So it was about $30,000 a year for four years. So it was about $120,000, okay? So roughly speaking, I gave my college about $120,000. Okay, so you might say that I already gave them $120,000 and now you have the audacity to ask me for more money.",
                    "What is college? Stop going until we figure it out. Because I went to college, I have no idea what it was. I went to college, I was 18 years old, I looked like I was 11. I lived like a goddamn Ninja Turtle. I didn’t drink water the entire time. I lived on cigarettes and alcohol and Adderall.",
                    "College was like a four-year game show called Do My Friends Hate Me or Do I Just Need to Go to Sleep? But instead of winning money, you lose $120,000.",
                    "How dare you clap? How dare you clap for the worst financial decision I ever made in my life? I paid $120,000 for someone to tell me to go read Jane Austen and then I didn’t.",
                    "That is way better than walking across a stage at graduation, hungover, in a gown, to accept a certificate for reading books that I didn’t read. Strolling across a stage, the sun in my eyes, my family watching as I sweat vodka and ecstasy, to receive a four-year degree in a language that I already spoke.",
                    "Dear IRS, please deduct from my federal income tax one XXL Billabong T-shirt from youth. It was too big. My mom said it could be a sleep shirt. Please deduct this from my 2017 income.",
                    "I’m gross. I have hair on my shoulders now. I don’t even have a joke for that. That’s how much I hate that shit.",
                    "I can’t listen to any new songs because every new song is about how tonight is the night and how we only have tonight. That is such 19-year-old horseshit.",
                    "I want to write songs for people in their 30s called 'Tonight’s No Good, How About Wednesday? Oh, You’re in Dallas on Wednesday? Okay. Well, Let’s Just Not See Each Other for Eight Months And It Doesn’t Matter at All.'",
                    "I smell a robot. Prove, prove, prove. Prove to me you’re not a robot. Look at these curvy letters. Much curvier than most letters, wouldn’t you say? No robot could ever read these. You look, mortal, if ye be. You look and then you type what you think you see. Is it an E or is it a 3? That’s up to ye. The passwords of past you’ve correctly guessed, but now it’s time for the robot test! I’ve devised a question no robot could ever answer. Which of these pictures does not have a stop sign in it?",
                    "When my wife walks down the street, she does not give a shit what anyone thinks of her in any situation. She’s my hero. When I walk down the street, I need everybody, all day long, to like me so much. It’s exhausting. My wife said that walking around with me is like walking around with someone who’s running for mayor of nothing.",
                    "My dad once grabbed me by the shirt and lifted me up during church and said, 'God can’t hear you.'",
                    "Bread is God is bread ♪ ♪ Is God is bread ♪ ♪ Is God is bread.",
                    "My vibe is more like, 'Hey, you could pour soup in my lap and I’ll probably apologize to you.'",
                    "I grew up Catholic. I don’t go to church anymore. But I went on Christmas Eve with my parents, ’cause you know how you lie to your parents. So… we go into the church and I was like, 'I got this under control.' And then I got schooled because they introduced a bunch of new shit.",
                    "Oh, yes, and what a mighty king I will be, eating dinner at 4:45 in the afternoon.",
                    "Craig and Stacia are looking for a two-story A-frame that’s near Craig’s job in the downtown, but also satisfies Stacia’s need to be near the beach which is nowhere near Craig’s job. With three children and nine on the way, and a max budget of $7, let’s see what Lori Jo can do on this week’s episode of You Don’t Deserve A Beach House.",
                    "No one wants to applaud the penis of a 32-year-old weirdo",
                    "Well… you know how I’m filled with rage? I’m so horny and angry all the time… and I have no outlet for it. So… eggs.",
                    "I don’t know. I know you told me. But I have had a very long day. I am very small. And I have no money. So you can imagine the kind of stress that I am under.",
                    "Hey, doesn’t anyone wanna know why… his dick was near my biters… in the first place? Isn’t anyone curious… as to how I had access?",
                    "We had a rule in our house, you were not allowed to watch TV on a school night. So, every school night, I would 100% be watching TV.",
                    "I worked at an office once on 57th Street in New York City. I was there for a couple weeks. I was in a cubicle next to this other cubicle. This woman named Mischa sat in the other cubicle. I want to get the number right. I think Mischa had… about 900,000 photos of her daughter up in her cubicle.",
                    "Like old, old, old money. Like, his money was in molasses or something.",
                    "Ah! One feels like a duck splashing around in all this wet! And when one feels like a duck, one is happy!",
                    "Too old to be a duckling. Quack, quack.",
                    "Eat ass, suck a dick and sell drugs.",
                    "Based on my ten-year-old memory, Bill Clinton is about 13 feet tall.",
                    "I’m either having a drink or I have to pee, you’re livin’ the golden years, kid, not me."
                ];
                var randomQuote = bestQuote[Math.floor(Math.random() * bestQuote.length)];
                msg.channel.send(randomQuote);
            break;
        case 'pr': 
            var prQuotes = [
                "Everywhere I go, I'm walking on red carpet.",
                "TREAT YO' SELF!",
                "Never half-ass two things. Whole-ass one thing.",
                "I'm a simple man. I like pretty, dark-haired women and breakfast food.",
                "I hate talking to people about things.",
                "When life gives you lemons, you sell some of your grandma's jewelry and you go clubbin'.",
                "I am big enough to admit that I'm often inspired by myself.",
                "I have no idea what I'm doing, but I know I'm doin git well.",
                "'Cause windows are the eyes to the house.",
                "If there were more food and fewer people, this would be a perfect party.",
                "Everything nurts and I'm dying.",
                "Sophisticated with a hint of slutty.",
                "You poetic, noble land mermaid.",
                "Time is money, money is power, power is pizza, and pizza is knowledge.",
                "Ovaries before brovaries",
                "My whole life is a giant mess and I love it.",
                "I hope you brought a change of clothes because your eyes are about to piss tears.",
                "I have never taken the high road. But I tell other people to ‘cause then there’s more room for me on the low road.",
                "I don't want to brag, but I've got a ton of experience with women being mad at me.",
                "I stand behind my decision to avoid salad and other disgusting things.",
                "You're as guilty as you are sexy.",
                "Warning: High levels of swagger coming through.",
                "Everything hurts. Running is impossible.",
                "BA-BA-BOOEY",
                "Clear alcohols are for rich women on diets.",
                "You are a beautiful, talented, brilliant, powerful musk ox.",
                "When April was born I was already in third grade, which means if we were friends back then I would have been hanging out with a baby. I don't know anything about infant care. Oh my god I could have killed her.",
                "I also think it's pointless for a human to paint scenes of nature when they can go outside and stand in it.",
                "Oh dude, you forgot to put a shirt on. Don't worry I do it all the time.",
                "Love…love fades away, but things…things are forever.",
                "Guys love it when you can show them you're better than they are at something they love.",
                "I think Comic Sans always screams FUN.",
                "Sometimes you gotta work a little so you can ball a lot.",
                "The less I know about other people’s affairs, the happier I am. I’m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
                "Veganism is the sad result of a morally corrupt mind. Reconsider your life.",
                "I love games that turn people against each other.",
                "When I walked in this morning I saw that the flag was at half mast, I thought, ‘All right, another bureaucrat ate it!’ And then I saw it was Lil’ Sebastian. Half-mast is too high. Show some damn respect.",
                "One time I accidentally drank an entire bottle of vinegar. I thought it was terrible wine.",
                "You may have thought you heard me say I wanted a lot of bacon and eggs, but what I said was: Give me all the bacon and eggs you have.",
                "Fishing relaxes me. It’s like yoga, except I still get to kill something.",
                "I don’t even want to be here. The air is too fresh. It’s disgusting. I can’t breathe.",
                "When life gives you lemons make lemonade. I read that one on a can of lemonade. I like to think it applies to life.",
                "We have to remember what’s important in life: friends, waffles, and work. Or waffles, friends, work. But work has to come third.",
                "There has never been a sadness that can’t be cured by breakfast food.",
                "I'm allergic to sushi. Every time I eat more than 80 pieces, I barf.",
                "Dress code? Black tie optional. Just like life.",
                "What I hear when I'm being yelled at is people caring loudly at me.",
                "Behind every successful man is me, smiling and taking partial credit.",
                "I don’t care about that prize. But I’m gonna win because I want his happiness to go away.",
                "I hope no one minds if I live tweet this bitch",
                "The bankrupt government of Pawnee has been shut down all summer so it's been three months of no work, no meetings, no memos, no late nights, nothing. I wouldn't wish it on my worst enemy.",
                "I wonder who else was born in Eagleton. Voldemort, probably.",
                "Do you have a first date outfit I could borrow? Like, I don't know a pair of cargo pants?",
                "I call this turf 'n' turf. It's a 16-ounce T-bone and a 24-ounce porterhouse. Also, whisky and a cigar. I am going to consume all of this at once because I am a free American.",
                "There’s a booth over there selling something called 'fried sausage quilts,' so I’m going to buy the booth.",
                "I guess some people object to powerful depictions of awesome ladies.",
                "Well I am not usually one for speeches. So, Goodbye.",
                "I love you and I like you.",
            ];
            var randomPR = prQuotes[Math.floor(Math.random() * prQuotes.length)];
            msg.channel.send(randomPR);
            break;
               

        case 'lily': 
            var puns = [
                "To whoever took my Microsoft Office: I will find you. You have my Word.",
                "The number of people who confuse too and to is two damn high.",
                "A scarecrow says, 'This job isn't for everyone, but hay, it's in my jeans.'",
                "What do you do with a dead chemist? You barium",
                "Did you hear about the guy who lost the left side of his body? He's alright now.",
                "I did a theatrical performance on puns. It was a play on words",
                "I bet the person who created the door knocker won a Nobel prize.",
                "Did you hear about the cheese factory that exploded in france? There was nothing but des brie.",
                "Why did one banana spy on the other? Because she was appealing.",
                "I used to be afraid of hurdles, but I got over it.",
                "I read a book on anti-gravity. I couldn’t put it down.",
                "What did the buffalo say to his son? Bison.",
                "I couldn’t remember how to throw a boomerang but it came back to me.",
                "What should you do if you’re cold? Stand in the corner. It’s 90 degrees.",
                "What did the alien say to the pitcher of water? Take me to your liter.",
                "Sausage puns are the wurst.",
                "Whiteboards are remarkable.",
                "Geology rocks.",
                "Time flies like an arrow, fruit flies like a banana.",
                "I, for one, like roman numerals.",
                "Walking on the shore I spotted a gigantic clam. I tried to drag it back home but I had to stop cause I pulled a mussel.",
                "I entered a joke competition once with 10 puns. Thought I'd win, but no pun in ten did.",
                "I had this great idea for a belt made of watches, but I gave it up when I realized that it would be a waist of time.",
                "I have a logic fetish. I can't stop coming to conclusions.",
                "My wedding day was so emotional, even the cake was in tiers.",
                "My cat was just sick on the carpet, I don’t think it’s feline well.",
                "There’s a new type of broom out, it’s sweeping the nation.",
                "Have you ever heard of a music group called Cellophane? They mostly wrap.",
                "The shovel was a ground breaking invention.",
                "Why should you never trust a train? They have loco motives.",
                "Is your refrigerator running? Better go catch it.",
                "I saw an ad for burial plots, and thought to myself this is the last thing I need.",
                "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
                "Have you ever tried to eat a clock? It's very time consuming.",
                "Yesterday a clown held the door for me. It was a nice jester.",
                "What does a house wear? A dress.",
                "What do you receive when you ask a lemon for help? Lemonaid.",
                "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
                "An untalented gymast walks into a bar.",
                "Einstein developed a theory about space, and it was about time too.",
                "My friends say they don’t like skeleton puns. I should put more backbone into them.",
                "Never discuss infinity with a mathematician, they can go on about it forever.",
                "Why don’t some couples go to the gym? Because some relationships don’t work out.",
                "People say i look better without glasses but i just can't see it.",
                "I changed my iPod name to Titanic. It’s syncing now.",
                "I smeared some ketchup all over my eyes once. It was a bad idea in Heinz- sight.",
                "Novice pirates make terrible singers because they can’t hit the high seas.",
                "I told my friend she drew her eyebrows too high. She seemed surprised.",
                "I got a master’s degree in being ignored; no one seems to care.",
                "Simba, you're falling behind. I must ask you to Mufasa.",
                "The bomb didn't want to go off. So it refused.",
                "I feel sorry for shopping carts. They’re always getting pushed around.",
                "The lumberjack loved his new computer. He especially enjoyed logging in.",
                "Sleeping comes so naturally to me, I could do it with my eyes closed.",
                "I really look up to my tall friends.",
                "Long fairy tales have a tendency to dragon."
            ];
            var randomPuns = puns[Math.floor(Math.random() * puns.length)];
            msg.channel.send(randomPuns);
            break;

        case 'ali': 
            var aliWong = [
                "A lot of people like to ask me ‘Ali, how on earth do you balance family and career?’ Men never get asked that question. Because they don’t. My husband occasionally changes diapers, and when people hear that, confetti everywhere. When my baby girl was first born I would do skin-on-skin contact everyday to bond with her. She shit on my chest. Where’s my confetti?",
                "My nanny is 62 years old. I would never hire anything younger than 62 years old. If you are hiring a 25-year-old pretty young thing to be your nanny, you’re a dumbass.",
                "I used to hate on other moms for the clothes that they wore, you know, all the cheesy-ass animal print and loud metallic shiny shoes, and now I see something that’s bedazzled in rhinestones and I’m like ‘oh that looks nice, I think I’m gonna get that,’ because when you’re a mom you need sparkle to compensate for the light inside of you that has died.",
                "If you haven’t licked ass yet, grow up, grow the fuck up and learn how to be in a committed relationship where you have to make sacrifices for the greater good.",
                "Maternity leave is not just to bond with the baby, fuck the baby. Maternity leave is for new moms to hide and heal their demolished-ass bodies. I couldn’t go back to work topless beating my wet titty trying to establish dominance over my co-workers.",
                "It’s so sexist when people ask me, well, if you’re here, then who’s taking care of the baby? Who the fuck do you think is taking care of the baby? The TV is taking care of the baby, okay? The windows are open, she’s got gummy bear vitamins on her lap, she’s fine.",
                "With a human baby, you just have to guess and check your intuition by sniffing its ass 26 times a day, and you can’t phone it in and sniff it from afar. You really gotta flip the baby over and plant your face in the baby’s ass and give it a good yoga inhale with your mouth.",
                "That’s how I know I love my baby more than anybody else in the entire world. I told my husband 'till death do us part,’ and not once have I ever sniffed his ass to check if he shit his pants.",
                "Breastfeeding is this savage ritual that just reminds you that your body is a cafeteria now.",
                "When my baby girl would get hungry she would yank my nipple back and forth like that bear fucking up Leonardo Dicaprio in 'The Revenant.' It’s frightening. I saw that movie and my nipples were like, ‘I feel you, Leo!’",
                "My mom saw me struggle with breastfeeding and she was very discouraging about it. She was like, ‘Why are you breastfeeding? I raised you on formula and look how shiny your hair is.’ She was like, ‘Are you falling for that bullshit slogan, breast is best?’ I was like ‘No, I do it because breast is free.’",
                "They put the anesthesia in your back, and then they put up this curtain so that your husband can only see your human side, and not your cadaver side. And then 10 minutes later they hold the baby above the curtain like bloody Simba and its over.",
                "If I ever do a nude scene, I want to be in shape just enough so nobody calls me 'courageous' for doing it.",
                "Because 18-year-old girls, they could just eat like shit, and then they take a shit nad have a six-pack.",
                "Bathroom stalls w/o purse hooks are fucking primitive. My mom didn't come to this country so I could shit with my backpack on.",
                "DIY stands for 'you should've married someone with more money'",
                "Everybody has HPV, OK? Everybody has it. It’s OK. Come out already. Everybody has it. If you don’t have it yet, you go and get it. You go and get it. It’s coming. You don’t have HPV yet, you’re a fucking loser, all right?",
                "I can also tell that I’m getting older, because my Kindle is turning into a self-help library. I’m not interested in books like Fifty Shades of Grey, OK? I’m interested in The Life-Changing Magic of Tidying Up. Yes. Yes, that’s right, how to declutter my home to achieve inner peace and my optimum level of success.",
                "That’s what your 30s is all about. How can I turn this shit around? I’m a horrible person, I’m not happy with where I am, how can I turn this shit around? Help me, Tony Robbins, help me!",
                "I’m hoping that if the hoarding goes away, the HPV will also disappear.",
                "You wanna be a grown-ass woman, stop dating skaters. Stop dating skaters unless you wanna wake up on a mattress in a kitchen. They’re sexy on the outside, malt liquor on the inside. Horrible.",
                "That store Urban Outfitters has made things very confusing for my generation. You homeless or you a hipster? Is that beard for fashion or for warmth?",
                "You go to any hipster neighborhood in a major city in America and that shit is turning into a Yoko Ono factory.",
                "And you know, white dudes, they teach you about a lot of cool stuff like voting and recycling, and disturbing documentaries.",
                "I mean, nothing makes me feel more powerful than when a white dude eats my pussy. Oh, my God. I just feel like I’m absorbing all of that privilege and all of that entitlement, you know, just right there, through the money hole and just... And then also, he’s so vulnerable down there. I’m, like, 'I could just crush your head at any moment, white man! I could just kill you right now! Crush those brains! Colonize the colonizer!' You know?",
                "Asian men are the sexiest. They got no body hair from the neck down. It’s like making love to a dolphin. Oh, my God. It’s so smooth, just like a slip and slide. Just black fish, Tilikum, all up in my bed every night, you know?",
                "You mess with a Jewish dude and your body is all fucked up afterwards. It’s all red and inflamed and you’re like, 'I did not ask to be exfoliated today. This is the last time I go on J-date, more like loofah date. Thanks for the rug burn, Avi.",
                "Asian men, no body odor. None. They just smell like responsibility. That’s where the umami flavor comes from.",
                "The fancy Asians are the Chinese, the Japanese. They get to do fancy things like host Olympics. Jungle Asians host diseases.",
                "When I pee, I need to see ten gallons of bleach, an ATM machine and a grandma with glaucoma napping in the corner. And the wait staff here is too nice. We need to leave this restaurant deaf and emotionally abused.",
                "But sometimes, all of this hippy-dippy shit we do makes me feel like we are white people doing an impression of Asian people. Like, we have these Chinese scrolls up on the wall and neither of us know what the fuck they mean. We’re like, 'Oh, that seems to go very well with our Buddha piggy bank from Pier 1 Imports. That seems to be providing some good feng shui for the house.'",
                "That’s how proposals really work, OK? A woman has to incept the idea into the man’s head. First passively and then if he doesn’t get the message, extremely aggressively. You gotta threaten to leave without ever actually leaving, because you know that you’re too old and it’s too late to go back out there and find a new man and start the whole manipulation cycle all over again.",
                "I’ve been reading that book by Sheryl Sandberg, she’s the C.O.O. of Facebook, and she wrote that book that got women all riled up about our careers. Talking about how we as women should challenge ourselves to sit at the table and rise to the top. And her book is called Lean In. Well, I don’t wanna lean in, OK? I wanna lie down. I want to lie the fuck down.",
                "I think feminism is the worst thing that ever happened to women. Our job used to be no job. We had it so good. We could have done the smart thing, which would have been to continue playing dumb for the next century and be like, 'We’re dumb women. We don’t know how to do anything. So, I guess we better just stay at home all day and eat snacks and watch Ellen. Cause we're too stupid to have any real responsibility.", 
                "Oh, you don’t think women had a lot of options when our day was free? Unscheduled, unsupervised, and most importantly, sponsored? Do you know how much shittier food tastes when you know you have to earn it?",
                "Housewives, they don’t gotta shit in a office. Housewives get to shit in their house. Skin to seat. They don’t gotta use that horrible toilet paper cover.",
                "I literally spat on my toilet paper two days ago, to try to make a MacGyver baby wipe, to moisten it, and then it backfired ’cause my fingers broke through and digitally stimulated more doo doo to come out, and then I had to start all over again. And you can never finish wiping at work because you always feel rushed ’cause you’re paranoid that your co-worker’s gonna recognize your shoes underneath the stall.",
                "Housewives, they don’t gotta muffle their shit, too. They don’t gotta worry about the velocity with which their doo doo comes out. They don’t gotta try to, you know, squeeze the butt cheeks together to make sure that the doo doo comes out at a slow and steady pace, so that no unpredictable noise suddenly escapes and brings you deep, deep shame. Housewives are free to just blow ass into the toilet and let it echo and reverberate to the ends of their hallways while watching as much Netflix on their iPad as they want. They don’t gotta take these boring, repressed shits. They can listen to podcasts. Planet Money. They can do whatever they want.",
                "You need to eat bananas.",
                "I saw those green ballet flats. I know that shit was you. Don’t try to tell me to get my shit together when I heard you not have your shit together",
                "Just choke me enough so that I can’t talk. ‘Cause if I can talk, I’m gonna tell you what to do. And I’m tired of being the boss. I’m the boss all the time, so, in the bedroom, you be the boss. Yes. Because I’m the real boss. And I told you so, motherfucker, so do it.",
                "I’m just waiting for the right moment to, like, become a housewife, financially, you know? I want my husband to get us to, like, a certain point financially. I wanna get to the point as a couple where I can comfortably afford sliced mango. Know what I’m talking about? I’m talking about that Whole Foods mango. That $10-a-box Whole Foods mango that was sliced by white people. That’s the kind of income bracket I’m striving for. That’s when you know you’ve made it, when you’re eating mango that was sliced by a dude named Noah. I want Noah mango, Rebecca kiwi, Danielle pineapple.",
                "I wanna be able to take a stroll on a sidewalk, see a quarter, and just keep on walking. Like a princess.",
                "I have some useful advice for all my Asian-American brothers and sisters. Yeah! Never go paintballing with a Vietnam veteran.",
                "Well, Asian don’t die. We don’t die. Especially the women, we live forever. And you know why we’re such bad drivers? Because we’re trying to die.",
                "Every time I get into a car accident I need to hide my face so that everybody doesn’t see that it’s what everybody thought it was gonna be. So embarrassing. My Toyota Corolla is a mess. There’s this huge bear claw scratch on the side from this aggressive brick wall that came out of nowhere. And then, on the hood, there’s multiple hand prints from pedestrians who have had to alert me of their existence.",
                "My mom is 80, going through a full blown mid-life crisis. ‘Cause she knows that she’s got a century more to go. And she is so lonely.",
                "Do you remember when you were 18 years old, and your pussy was just sopping wet all the time? All the time, you just took it for granted that you could just reach your hand down your pants at any given moment, you throw up the peace sign afterwards, and there would be that snail-trail in between your fingers. Oh, my God, it was so juicy. You could just blow a bubble wand with it, just… 'I slime you, I slime you. Ghostbusters!'",
                "So, then I had to find ways to discretely scratch myself underneath the conference table, and then resist the urge to immediately smell my fingers afterwards.",
                "When somebody closes their eyes during sex, it’s not because they’re in such ecstasy with you that– that they need to close their eyes. When somebody closes their eyes during sex, it’s because they’re literally trying to shut the image of your face out of their head and instead project two Latina lesbians that they saw earlier that day on RedTube onto the back of their eyelids.",
                "If you shat juicy hamburgers would you ever wait in line at In-N-Out again? No, you would pop a squat over your husband’s head every morning. And tell him to open wide because breakfast is on the way, animal style.",
                "If we had hired a 25-year-old man, who was… not ugly… Great with my daughter and said yes immediately to every chore I asked him to do with a positive attitude, Oh, you best believe that I would eat the shit out of his butthole. Every day. Every day would be an all-day nanny butthole buffet.",
                "What do your oppressive Asian parents who beat you with the SAT book until your fingers bled from playing the cello think about your butthole-licking jokes?",
                "Because everybody knows the secret now that when a woman sleeps with a man right away, it’s not because we don’t respect ourselves, it’s because we don’t respect you. We don’t see you as marriage material. That’s why we let your dick inside so fast.",
                "When a man doesn’t sleep with you right away, oh… oh, it’s not because he respects you, it’s because he has a small dick. And he’s trying to trap you. Do not fall for that trap.",
                "Look, I love Groupon, okay? But it was so depressing and demoralizing to see my face and my picture next to whale watching tours, teeth whitening services, and discontinued dildos on clearance.",
                "Ethnic studies is a major where you study how to blame everything on white people.",
                "Yeah, I’m a real dummy. I don’t know the alphabet, I don’t know how to count, I don’t know the difference between shapes and colors. I can’t be trusted to deposit checks or do anything important, for I am just a simple ho.",
                "After I filmed Baby Cobra, Netflix sent me a Netflix baby onesie and a basket. You know those baskets that white people like to give with the biscotti, and the cheese, and the caramel popcorn, and all the other shit that Asian people have no interest in whatsoever.",
                "You think I wanna fuck an 18-year-old boy when I’m on the precipice of menopause? Have some nervous teenager do three pumps and then bust a nut in my old-ass pussy? No, thank you. No gracias. I don’t wanna fuck an 18-year-old boy, not now, not ever again, because they’re 18, they’re terrible in bed.",
                "Do you remember when we were all teenagers? It was horrible for teenage girls because oral sex was all one-way. As a teenage girl, you never ever got your pussy eaten, but you sucked so many dicks. You’d suck a dick under a bridge, in the bathroom, in the forest. But as a teenage girl, you never just casually got your pussy eaten behind the bleachers.",
                "I fart in my husband.",
                "Do you know how long it took me to train my husband to eat my pussy correctly? I’m not going back out into the world, find somebody new to coach all over again. It’s too much work. All of that knowledge that my husband has now, all that time I invested, all of that muscle memory lives and dies with him.",
                "I think a big part of being good at eating pussy is that you just got to be into it, okay? Do it with gusto, with enthusiasm. It’s a privilege, so act like you know, okay? Yes! Yeah, don’t hesitate. Don’t… Like you’re some toddler being forced to eat broccoli. Get in there! And hold your own goddamn head up, too, don’t use my thigh as a tripod.",
                "Lately, I have been ruminating a lot over this one time I hooked up with this dude, and in the middle of kissing, I felt the responsibility to stop and say, 'Hey, I should really let you know now before we go any further that… I’m on my period.' And he was like, 'Oh… Well… Then let’s make a fucking mess, Ali!' To this day, that is the most romantic thing anybody has ever said to me. I think about it when I feel down and ugly and no good. All I have to do is remember that there was once a man out there who was willing to yank out my tampon and replace it with his dick! It made me feel beautiful. Beautiful!",
                "Since I got married last year, I’ve been eating fried chicken skin every day since. That’s right. And just fulfilling my destiny. Which is to turn into a circle with eyelashes. Like Mrs. Pacman."
            ]
            var aliWongPuns = aliWong[Math.floor(Math.random() * aliWong.length)];
            msg.channel.send(aliWongPuns);
            break;
                
     case 'fuwu': 
            var facesAll = [
                "(* ^ ω ^)",
                "(´ ∀ ` *)",
                "٩(◕‿◕｡)۶",
                "☆*:.｡.o(≧▽≦)o.｡.:*☆",
                "(o^▽^o)",
                "(⌒▽⌒)☆",
                "<(￣︶￣)>",
                "。.:☆*:･'(*⌒―⌒*)))",
                "ヽ(・∀・)ﾉ",
                "(´｡• ω •｡`)",
                "(￣ω￣)",
                "｀;:゛;｀;･(°ε° )",
                "(o･ω･o)",
                "(＠＾◡＾)",
                "ヽ(*・ω・)ﾉ",
                "(o_ _)ﾉ彡☆",
                "(^人^)",
                "(o´▽`o)",
                "(*´▽`*)",
                "｡ﾟ( ﾟ^∀^ﾟ)ﾟ｡",
                "( ´ ω ` )",
                "(((o(*°▽°*)o)))",
                "(≧◡≦)",
                "(o´∀`o)",
                "(´• ω •`)",
                "(＾▽＾)",
                "(⌒ω⌒)",
                "∑d(°∀°d)",
                "╰(▔∀▔)╯",
                "(─‿‿─)",
                "(*^‿^*)",
                "ヽ(o^ ^o)ﾉ",
                "(✯◡✯)",
                "(◕‿◕)",
                "(*≧ω≦*)",
                "(☆▽☆)",
                "(⌒‿⌒)",
                "＼(≧▽≦)／",
                "ヽ(o＾▽＾o)ノ",
                "☆ ～('▽^人)",
                "(*°▽°*)",
                "٩(｡•́‿•̀｡)۶",
                "(✧ω✧)",
                "ヽ(*⌒▽⌒*)ﾉ",
                "(´｡• ᵕ •｡`)",
                "( ´ ▽ ` )",
                "(￣▽￣)",
                "╰(*´︶`*)╯",
                "ヽ(>∀<☆)ノ",
                "o(≧▽≦)o",
                "(☆ω☆)",
                "(っ˘ω˘ς )",
                "＼(￣▽￣)／",
                "(*¯︶¯*)",
                "＼(＾▽＾)／",
                "٩(◕‿◕)۶",
                "(o˘◡˘o)",
                "\(★ω★)/",
                "\(^ヮ^)/",
                "(〃＾▽＾〃)",
                "(╯✧▽✧)╯",
                "o(>ω<)o",
                "o( ❛ᴗ❛ )o",
                "｡ﾟ(TヮT)ﾟ｡",
                "( ‾́ ◡ ‾́ )",
                "(ﾉ´ヮ`)ﾉ*:･ﾟ",
                "(b ᵔ▽ᵔ)b",
                "(๑˃ᴗ˂)ﻭ",
                "(๑˘︶˘๑)",
                "( ˙꒳​˙ )",
                "(*꒦ິ꒳꒦ີ)",
                "°˖✧◝(⁰▿⁰)◜✧˖°",
                "(´･ᴗ･ ` )",
                "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
            ];
            var faces = facesAll[Math.floor(Math.random() * facesAll.length)];
            msg.channel.send(faces);
            break;
            // Just add any case commands if you want to..
         }
     }
});
bot.login(process.env.BOT_TOKEN);
